/** Generated by YAKINDU Statechart Tools code generator. */
package microwave.microwave;

import microwave.ITimer;

public class MicrowaveStatemachine implements IMicrowaveStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private SCInterfaceOperationCallback operationCallback;
		
		public void setSCInterfaceOperationCallback(
				SCInterfaceOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
		private boolean high;
		
		public void raiseHigh() {
			high = true;
			runCycle();
		}
		
		private boolean low;
		
		public void raiseLow() {
			low = true;
			runCycle();
		}
		
		private boolean digit;
		
		private long digitValue;
		
		public void raiseDigit(long value) {
			digit = true;
			digitValue = value;
			runCycle();
		}
		
		protected long getDigitValue() {
			if (! digit ) 
				throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
			return digitValue;
		}
		
		private boolean timer;
		
		public void raiseTimer() {
			timer = true;
			runCycle();
		}
		
		private boolean start;
		
		public void raiseStart() {
			start = true;
			runCycle();
		}
		
		private boolean stop;
		
		public void raiseStop() {
			stop = true;
			runCycle();
		}
		
		private boolean open;
		
		public void raiseOpen() {
			open = true;
			runCycle();
		}
		
		private boolean close;
		
		public void raiseClose() {
			close = true;
			runCycle();
		}
		
		private long power;
		
		public long getPower() {
			return power;
		}
		
		public void setPower(long value) {
			this.power = value;
		}
		
		protected void clearEvents() {
			high = false;
			low = false;
			digit = false;
			timer = false;
			start = false;
			stop = false;
			open = false;
			close = false;
		}
	}
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		microwave_Open,
		microwave_Open_Open_open,
		microwave_Close,
		microwave_Close_Close_Cooking,
		microwave_Close_Close_Cooking_Cooking_close,
		microwave_Close_Close_Cooking_Cooking_High,
		microwave_Close_Close_Cooking_Cooking_low,
		microwave_Close_Close_Cooking_Cooking_Timer,
		microwave_Close_Close_Cooking_Cooking_Start,
		microwave_Close_Close_Cooking_Cooking_beepOn,
		microwave_Close_Close_Cooking_Cooking_beepOff,
		$NullState$
	};
	
	private State[] historyVector = new State[2];
	private final State[] stateVector = new State[1];
	
	private int nextStateIndex;
	
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[3];
	private long control;
	
	protected void setControl(long value) {
		control = value;
	}
	
	protected long getControl() {
		return control;
	}
	
	private long countCookingTime;
	
	protected void setCountCookingTime(long value) {
		countCookingTime = value;
	}
	
	protected long getCountCookingTime() {
		return countCookingTime;
	}
	
	public MicrowaveStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCInterface.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCInterface must be set.");
		}
		
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NullState$;
		}
		for (int i = 0; i < 2; i++) {
			historyVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setPower(0);
		
		setControl(0);
		
		setCountCookingTime(5);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_Microwave_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case microwave_Open_Open_open:
				microwave_Open_Open_open_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_close:
				microwave_Close_Close_Cooking_Cooking_close_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_High:
				microwave_Close_Close_Cooking_Cooking_High_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_low:
				microwave_Close_Close_Cooking_Cooking_low_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_Timer:
				microwave_Close_Close_Cooking_Cooking_Timer_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_Start:
				microwave_Close_Close_Cooking_Cooking_Start_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_beepOn:
				microwave_Close_Close_Cooking_Cooking_beepOn_react(true);
				break;
			case microwave_Close_Close_Cooking_Cooking_beepOff:
				microwave_Close_Close_Cooking_Cooking_beepOff_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_Microwave();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case microwave_Open:
			return stateVector[0].ordinal() >= State.
					microwave_Open.ordinal()&& stateVector[0].ordinal() <= State.microwave_Open_Open_open.ordinal();
		case microwave_Open_Open_open:
			return stateVector[0] == State.microwave_Open_Open_open;
		case microwave_Close:
			return stateVector[0].ordinal() >= State.
					microwave_Close.ordinal()&& stateVector[0].ordinal() <= State.microwave_Close_Close_Cooking_Cooking_beepOff.ordinal();
		case microwave_Close_Close_Cooking:
			return stateVector[0].ordinal() >= State.
					microwave_Close_Close_Cooking.ordinal()&& stateVector[0].ordinal() <= State.microwave_Close_Close_Cooking_Cooking_beepOff.ordinal();
		case microwave_Close_Close_Cooking_Cooking_close:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_close;
		case microwave_Close_Close_Cooking_Cooking_High:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_High;
		case microwave_Close_Close_Cooking_Cooking_low:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_low;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_Timer;
		case microwave_Close_Close_Cooking_Cooking_Start:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_Start;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_beepOn;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			return stateVector[0] == State.microwave_Close_Close_Cooking_Cooking_beepOff;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseHigh() {
		sCInterface.raiseHigh();
	}
	
	public void raiseLow() {
		sCInterface.raiseLow();
	}
	
	public void raiseDigit(long value) {
		sCInterface.raiseDigit(value);
	}
	
	public void raiseTimer() {
		sCInterface.raiseTimer();
	}
	
	public void raiseStart() {
		sCInterface.raiseStart();
	}
	
	public void raiseStop() {
		sCInterface.raiseStop();
	}
	
	public void raiseOpen() {
		sCInterface.raiseOpen();
	}
	
	public void raiseClose() {
		sCInterface.raiseClose();
	}
	
	public long getPower() {
		return sCInterface.getPower();
	}
	
	public void setPower(long value) {
		sCInterface.setPower(value);
	}
	
	private boolean check_Microwave_Close_Close_Cooking_Cooking__choice_0_tr0_tr0() {
		return sCInterface.getPower()==1;
	}
	
	private boolean check_Microwave_Close_Close_Cooking_Cooking__choice_0_tr1_tr1() {
		return sCInterface.getPower()==2;
	}
	
	private void effect_Microwave_Close_Close_Cooking_Cooking__choice_0_tr0() {
		enterSequence_Microwave_Close_Close_Cooking_Cooking_High_default();
	}
	
	private void effect_Microwave_Close_Close_Cooking_Cooking__choice_0_tr1() {
		enterSequence_Microwave_Close_Close_Cooking_Cooking_low_default();
	}
	
	/* Entry action for state 'open'. */
	private void entryAction_Microwave_Open_Open_open() {
		sCInterface.operationCallback.stopCook();
		
		sCInterface.operationCallback.openDoor();
		
		sCInterface.operationCallback.display("WAITING");
	}
	
	/* Entry action for state 'close'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_close() {
		sCInterface.operationCallback.clearDisplay();
		
		sCInterface.operationCallback.closeDoor();
	}
	
	/* Entry action for state 'High'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_High() {
		sCInterface.operationCallback.display("HIGH");
	}
	
	/* Entry action for state 'low'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_low() {
		sCInterface.operationCallback.display("LOW");
	}
	
	/* Entry action for state 'Timer'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_Timer() {
		sCInterface.operationCallback.displayTime(getControl());
	}
	
	/* Entry action for state 'Start'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_Start() {
		timer.setTimer(this, 0, (1 * 1000), false);
		
		sCInterface.operationCallback.cook();
		
		sCInterface.operationCallback.displayTime(getControl());
	}
	
	/* Entry action for state 'beepOn'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_beepOn() {
		timer.setTimer(this, 1, (1 * 1000), false);
		
		sCInterface.operationCallback.beepOn();
		
		sCInterface.operationCallback.display("FINISHED");
	}
	
	/* Entry action for state 'beepOff'. */
	private void entryAction_Microwave_Close_Close_Cooking_Cooking_beepOff() {
		timer.setTimer(this, 2, (5 * 1000), false);
		
		sCInterface.operationCallback.beepOff();
		
		sCInterface.operationCallback.display("FINISHED");
	}
	
	/* Exit action for state 'Start'. */
	private void exitAction_Microwave_Close_Close_Cooking_Cooking_Start() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'beepOn'. */
	private void exitAction_Microwave_Close_Close_Cooking_Cooking_beepOn() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'beepOff'. */
	private void exitAction_Microwave_Close_Close_Cooking_Cooking_beepOff() {
		timer.unsetTimer(this, 2);
	}
	
	/* 'default' enter sequence for state Open */
	private void enterSequence_Microwave_Open_default() {
		enterSequence_Microwave_Open_Open_default();
	}
	
	/* 'default' enter sequence for state open */
	private void enterSequence_Microwave_Open_Open_open_default() {
		entryAction_Microwave_Open_Open_open();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Open_Open_open;
	}
	
	/* 'default' enter sequence for state Close */
	private void enterSequence_Microwave_Close_default() {
		enterSequence_Microwave_Close_Close_default();
	}
	
	/* 'default' enter sequence for state Cooking */
	private void enterSequence_Microwave_Close_Close_Cooking_default() {
		enterSequence_Microwave_Close_Close_Cooking_Cooking_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state close */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_close_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_close();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_close;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state High */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_High_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_High();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_High;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state low */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_low_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_low();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_low;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Timer */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_Timer_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_Timer();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_Timer;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Start */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_Start_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_Start();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_Start;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state beepOn */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOn_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_beepOn();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_beepOn;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state beepOff */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOff_default() {
		entryAction_Microwave_Close_Close_Cooking_Cooking_beepOff();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Close_Close_Cooking_Cooking_beepOff;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		react_Microwave__entry_Default();
	}
	
	/* 'default' enter sequence for region Open */
	private void enterSequence_Microwave_Open_Open_default() {
		react_Microwave_Open_Open__entry_Default();
	}
	
	/* 'default' enter sequence for region Close */
	private void enterSequence_Microwave_Close_Close_default() {
		react_Microwave_Close_Close__entry_Default();
	}
	
	/* deep enterSequence with history in child Close */
	private void deepEnterSequence_Microwave_Close_Close() {
		switch (historyVector[0]) {
		case microwave_Close_Close_Cooking_Cooking_close:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_High:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_low:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_Start:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			deepEnterSequence_Microwave_Close_Close_Cooking_Cooking();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region Cooking */
	private void enterSequence_Microwave_Close_Close_Cooking_Cooking_default() {
		react_Microwave_Close_Close_Cooking_Cooking__entry_Default();
	}
	
	/* deep enterSequence with history in child Cooking */
	private void deepEnterSequence_Microwave_Close_Close_Cooking_Cooking() {
		switch (historyVector[1]) {
		case microwave_Close_Close_Cooking_Cooking_close:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_close_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_High:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_High_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_low:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_low_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_Timer_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_Start:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_Start_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOn_default();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOff_default();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for state Open */
	private void exitSequence_Microwave_Open() {
		exitSequence_Microwave_Open_Open();
	}
	
	/* Default exit sequence for state open */
	private void exitSequence_Microwave_Open_Open_open() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Close */
	private void exitSequence_Microwave_Close() {
		exitSequence_Microwave_Close_Close();
	}
	
	/* Default exit sequence for state close */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_close() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state High */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_High() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state low */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_low() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Timer */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Start */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_Start() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Close_Close_Cooking_Cooking_Start();
	}
	
	/* Default exit sequence for state beepOn */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOn() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Close_Close_Cooking_Cooking_beepOn();
	}
	
	/* Default exit sequence for state beepOff */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOff() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Close_Close_Cooking_Cooking_beepOff();
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		switch (stateVector[0]) {
		case microwave_Open_Open_open:
			exitSequence_Microwave_Open_Open_open();
			break;
		case microwave_Close_Close_Cooking_Cooking_close:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_close();
			break;
		case microwave_Close_Close_Cooking_Cooking_High:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_High();
			break;
		case microwave_Close_Close_Cooking_Cooking_low:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_low();
			break;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer();
			break;
		case microwave_Close_Close_Cooking_Cooking_Start:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOn();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOff();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Open */
	private void exitSequence_Microwave_Open_Open() {
		switch (stateVector[0]) {
		case microwave_Open_Open_open:
			exitSequence_Microwave_Open_Open_open();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Close */
	private void exitSequence_Microwave_Close_Close() {
		switch (stateVector[0]) {
		case microwave_Close_Close_Cooking_Cooking_close:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_close();
			break;
		case microwave_Close_Close_Cooking_Cooking_High:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_High();
			break;
		case microwave_Close_Close_Cooking_Cooking_low:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_low();
			break;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer();
			break;
		case microwave_Close_Close_Cooking_Cooking_Start:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOn();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOff();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Cooking */
	private void exitSequence_Microwave_Close_Close_Cooking_Cooking() {
		switch (stateVector[0]) {
		case microwave_Close_Close_Cooking_Cooking_close:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_close();
			break;
		case microwave_Close_Close_Cooking_Cooking_High:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_High();
			break;
		case microwave_Close_Close_Cooking_Cooking_low:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_low();
			break;
		case microwave_Close_Close_Cooking_Cooking_Timer:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer();
			break;
		case microwave_Close_Close_Cooking_Cooking_Start:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOn:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOn();
			break;
		case microwave_Close_Close_Cooking_Cooking_beepOff:
			exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOff();
			break;
		default:
			break;
		}
	}
	
	/* The reactions of state null. */
	private void react_Microwave_Close_Close_Cooking_Cooking__choice_0() {
		if (check_Microwave_Close_Close_Cooking_Cooking__choice_0_tr0_tr0()) {
			effect_Microwave_Close_Close_Cooking_Cooking__choice_0_tr0();
		} else {
			if (check_Microwave_Close_Close_Cooking_Cooking__choice_0_tr1_tr1()) {
				effect_Microwave_Close_Close_Cooking_Cooking__choice_0_tr1();
			}
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Open_Open__entry_Default() {
		enterSequence_Microwave_Open_Open_open_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Close_Close_Cooking_Cooking__entry_Default() {
		enterSequence_Microwave_Close_Close_Cooking_Cooking_close_default();
	}
	
	/* Default react sequence for deep history entry  */
	private void react_Microwave_Close_Close__entry_Default() {
		/* Enter the region with deep history */
		if (historyVector[0] != State.$NullState$) {
			deepEnterSequence_Microwave_Close_Close();
		} else {
			enterSequence_Microwave_Close_Close_Cooking_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		enterSequence_Microwave_Close_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean microwave_Open_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Open_Open_open_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Open_react(try_transition)==false) {
				if (sCInterface.close) {
					exitSequence_Microwave_Open();
					sCInterface.operationCallback.closeDoor();
					
					react_Microwave_Close_Close__entry_Default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.open) {
					exitSequence_Microwave_Close();
					enterSequence_Microwave_Open_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_react(try_transition)==false) {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_close_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (sCInterface.low) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_close();
					sCInterface.setPower(2);
					
					react_Microwave_Close_Close_Cooking_Cooking__choice_0();
				} else {
					if (sCInterface.high) {
						exitSequence_Microwave_Close_Close_Cooking_Cooking_close();
						sCInterface.setPower(1);
						
						react_Microwave_Close_Close_Cooking_Cooking__choice_0();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_High_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (sCInterface.low) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_High();
					sCInterface.setPower(2);
					
					enterSequence_Microwave_Close_Close_Cooking_Cooking_low_default();
				} else {
					if (sCInterface.timer) {
						exitSequence_Microwave_Close_Close_Cooking_Cooking_High();
						enterSequence_Microwave_Close_Close_Cooking_Cooking_Timer_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_low_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_low();
					sCInterface.setPower(1);
					
					enterSequence_Microwave_Close_Close_Cooking_Cooking_High_default();
				} else {
					if (sCInterface.timer) {
						exitSequence_Microwave_Close_Close_Cooking_Cooking_low();
						enterSequence_Microwave_Close_Close_Cooking_Cooking_Timer_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_Timer_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (((sCInterface.digit) && (getControl()<1000))) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer();
					setControl(((control * 10) + sCInterface.getDigitValue()));
					
					enterSequence_Microwave_Close_Close_Cooking_Cooking_Timer_default();
				} else {
					if (sCInterface.start) {
						exitSequence_Microwave_Close_Close_Cooking_Cooking_Timer();
						enterSequence_Microwave_Close_Close_Cooking_Cooking_Start_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_Start_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (((timeEvents[0]) && (getControl()>0))) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
					setControl((control - 1));
					
					enterSequence_Microwave_Close_Close_Cooking_Cooking_Start_default();
				} else {
					if (getControl()==0) {
						exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
						sCInterface.operationCallback.stopCook();
						
						enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOn_default();
					} else {
						if (sCInterface.stop) {
							exitSequence_Microwave_Close_Close_Cooking_Cooking_Start();
							sCInterface.operationCallback.stopCook();
							
							setControl(0);
							
							enterSequence_Microwave_Close_Close_Cooking_Cooking_close_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_beepOn_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (timeEvents[1]) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOn();
					setCountCookingTime((countCookingTime - 1));
					
					enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOff_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Close_Close_Cooking_Cooking_beepOff_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Close_Close_Cooking_react(try_transition)==false) {
				if (((timeEvents[2]) && (getCountCookingTime()>=0))) {
					exitSequence_Microwave_Close_Close_Cooking_Cooking_beepOff();
					enterSequence_Microwave_Close_Close_Cooking_Cooking_beepOn_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
}
